apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservices.name }}-secrets
  namespace: {{ .Values.microservices.namespace }}
type: Opaque
data:
  MONGODB_USER: {{ .Values.secrets.MONGODB_USER }}
  MONGODB_PASSWORD: {{ .Values.secrets.MONGODB_PASSWORD }}
  

   
