apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-portal #deployment name
  namespace: grade-submission   #namepace
spec:   #specs contains replicas, labels
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: grade-submission-portal
  template:
    metadata:
      labels:  # Correct indentation
        app.kubernetes.io/name: grade-submission
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: grade-submission-portal
    spec:
      containers:
        - name: grade-submission-portal
          image: rslim087/kubernetes-course-grade-submission-portal
          env:
            - name: GRADE_SERVICE_HOST
              value: grade-submission-api
          resources:
            requests:  # Indented correctly under resources
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
          ports:
            - containerPort: 5001



# Selectors (spec.selector.matchLabels) → Deployment Level
  Defined in the Deployment spec.
  Determines which existing pods this deployment manages.
  Deployment looks for pods with these labels—if they don’t exist, it creates new ones.

# Labels in template.metadata.labels → Pod Level
  Inside the template section (under spec.template).
  Defines labels for the new pods created by this deployment.
  Ensures the generated pods match the selector.

