apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservices.name }}-secrets
  namespace: {{ .Values.microservices.namespace }}
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.secrets.MONGODB_URI }}
  

   
