apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservices.name }}
  namespace: {{ .Values.microservices.namespace }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Values.microservices.name }}
  ports:
  - port: {{ .Values.workload.port }}
    targetPort: {{ .Values.workload.port  }}
