apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace: grade-submission
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: grade-submission-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grade-submission
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: grade-submission-api
    spec:
      containers:
        - name: grade-submission-api
          image: rslim087/kubernetes-course-grade-submission-api:stateless-v3
          livenessProbe:   #here i added liveness probe
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
          env:
            - name: MONGODB_HOST
              value: mongodb #my db service-name
            - name: MONGODB_PORT
              value: '27017'
            - name: MONGODB_USER
              value: "admin"
            - name: MONGODB_PASSWORD
              value: "password123"
          resources:
            requests:  # Corrected indentation for resources
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"  # Added this as it is likely required
          ports:
            - containerPort: 3000  # Properly nested under the container
