useStatefulSet: true
auth:
  enabled: false
image:
  registry: docker.io
  repository: mongo
  tag: 6.0.4-jammy
persistent:
  mountPath: /data/db     #this way PV will be mounted correctly to local dir.
  
podSecurityContext:
  enabled: true
  fsGroup: 999
  runAsUser: 999
  runAsGroup: 999

containerSecurityContext:
  enabled: true
  runAsUser: 999
  runAsGroup: 999